spring:

  application:
    name: se-order-service

  config:
    import: "optional:consul:"

  cloud:
    consul:
      config:
        format: FILES
        fail-fast: false
        enabled: true
        prefix: config
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        healthCheckPath: ${server.servlet.context-path}/actuator/health
        healthCheckInterval: 15s
        prefer-ip-address: true
        register-health-check: true
        ip-address: ${spring.cloud.client.ip-address}
