server:
  port: 8082
  servlet:
    context-path: /product-service/api

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 30
      minimum-idle: 5
      leak-detection-threshold: 30000
      initialization-fail-timeout: 60000
      max-lifetime: 1800000
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  jackson:
    default-property-inclusion: non_null